development:
  cloud_name: "dqev3rwfk"
  api_key: "369884322226721"
  api_secret: "leCWC8dLDlDOXPisMNV6njsVU2E"

test:
  cloud_name: "dqev3rwfk"
  api_key: "369884322226721"
  api_secret: "leCWC8dLDlDOXPisMNV6njsVU2E"

production:
  cloud_name: "dqev3rwfk"
  api_key: "369884322226721"
  api_secret: "leCWC8dLDlDOXPisMNV6njsVU2E"
