Period.delete_all
Piece.delete_all
Profile.delete_all
User.delete_all
Role.delete_all

admin_role = Role.create(name: "Admin", description: "Administrator that can update pieces and manage members")
member_role = Role.create(name: "Member", description: "Member that can trade")
guest_role = Role.create(name: "Guest", description: "User is not logged in")

admin_user = User.create(email: "admin@cubicle.com", password: "adminadmin", role: admin_role )

ella = User.create( email: 'ella@dress.com', password: 'abcd1234', role: member_role )
julia = User.create( email: 'julia@dress.com', password: 'abcd1234', role: member_role )
stella = User.create( email: 'stella@dress.com', password: 'abcd1234', role: member_role )
emma = User.create( email: 'emma@dress.com', password: 'abcd1234', role: member_role )
eva = User.create( email: 'eva@dress.com', password: 'abcd1234', role: member_role )
elisa = User.create( email: 'elisa@dress.com', password: 'abcd1234', role: member_role )
leda = User.create( email: 'leda@dress.com', password: 'abcd1234', role: member_role )
louisa = User.create( email: 'louisa@dress.com', password: 'abcd1234', role: member_role )
hilda = User.create( email: 'hilda@dress.com', password: 'abcd1234', role: member_role )
janna = User.create( email: 'janna@dress.com', password: 'abcd1234', role: member_role )
pamina = User.create( email: 'pamina@dress.com', password: 'abcd1234', role: member_role )

p_admin = Profile.find_by(user: admin_user)
p_admin = p_admin.update( first_name: "Mark", surname: "Administrator" )

p_ella = Profile.find_by(user: ella)
p_ella = p_ella.update( first_name: "Ella", surname: "Jansen", date_of_birth: "1986-08-09", addr_street: "Kerkweg", addr_number: "23", postcode: "8763AA", addr_town: "Floningen aan de Waas", phone: "0687541234", gender: 'female', size: "S", fav_color: "red")
p_julia = Profile.find_by(user: julia)
p_julia = p_julia.update( first_name: "Julia", surname: "Bouwmeester", date_of_birth: "1977-04-24", addr_street: "Gen. Maczekstraat", addr_number: "88", postcode: "4444WS", addr_town: "Brabantdorp", phone: "0681542376", gender: 'female', size: "M", fav_color: "black")
p_stella = Profile.find_by(user: stella)
p_stella = p_stella.update( first_name: "Stella", surname: "Valk", date_of_birth: "1992-01-19", addr_street: "Groote Markt", addr_number: "23", postcode: "4833AA", addr_town: "Akkerhoeven", phone: "0648939812", gender: 'female', size: "XS", fav_color: "black")
p_emma = Profile.find_by(user: emma)
p_emma = p_emma.update( first_name: "Emma", surname: "Spaarland", date_of_birth: "1992-03-19", addr_street: "Terheijdenseweg", addr_number: "56", postcode: "4815HA", addr_town: "Monnenwolde", phone: "06498387388", gender: 'female', size: "M", fav_color: "grey")
p_elisa = Profile.find_by(user: elisa)
p_elisa = p_elisa.update( first_name: "Elisa", surname: "Landman", date_of_birth: "1990-04-16", addr_street: "Bisonstraat", addr_number: "6", postcode: "4891DD", addr_town: "Kaareind", phone: "0699223453", gender: 'female', size: "XL", fav_color: "blue")
p_leda = Profile.find_by(user: leda)
p_leda = p_leda.update( first_name: "Leda", surname: "Manveld", date_of_birth: "1982-05-23", addr_street: "Rozenlaan", addr_number: "87", postcode: "5333TY", addr_town: "Heidehoven", phone: "0384154632", gender: 'female', size: "L", fav_color: "blue")
p_louisa = Profile.find_by(user: louisa)
p_louisa = p_louisa.update( first_name: "Louisa", surname: "Veldakker", date_of_birth: "1979-03-30", addr_street: "Poolseweg", addr_number: "2B", postcode: "6533AD", addr_town: "Naareind", phone: "0631319400", gender: 'female', size: "M", fav_color: "white")
p_hilda = Profile.find_by(user: hilda)
p_hilda = p_hilda.update( first_name: "Hilda", surname: "Akkermans", date_of_birth: "1992-12-02", addr_street: "Hazelaarstraat", addr_number: "34", postcode: "5383WK", addr_town: "Wetten", phone: "0681449329", gender: 'female', size: "S", fav_color: "red")
p_janna = Profile.find_by(user: janna)
p_janna = p_janna.update( first_name: "Janna", surname: "Man", date_of_birth: "1985-10-09", addr_street: "Dijklaan", addr_number: "82", postcode: "5344GT", addr_town: "Oudehoeven", phone: "0675891196", gender: 'female', size: "XS", fav_color: "red")
p_pamina = Profile.find_by(user: pamina)
p_pamina = p_pamina.update( first_name: "Pamina", surname: "Ijssel", date_of_birth: "1998-08-22", addr_street: "Rembrandtstraat", addr_number: "1", postcode: "9287WW", addr_town: "Geendam", phone: "0683654453", gender: 'female', size: "M", fav_color: "black")

piece1 = Piece.create( { name: "Skeeter Mini Dress", brand: "Twin Sister", image: open("http://images.asos-media.com/inv/media/5/2/8/3/7053825/black/image1xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/5/2/8/3/7053825/image2xxl.jpg"), size: "S", colour: "black", price_cat: 3, user: ella } )
piece2 = Piece.create( { name: "Long Sleeve Knit Dress", brand: "YAS", image: open("http://images.asos-media.com/inv/media/5/9/1/1/6791195/black/image1xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/5/9/1/1/6791195/image3xxl.jpg"), size: "XS", colour: "grey", price_cat: 4, user: stella } )
piece3 = Piece.create( { name: "V neck Dress", brand: "W.I.T.", image: open("http://images.asos-media.com/inv/media/5/4/9/2/6712945/black/image1xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/5/4/9/2/6712945/image2xxl.jpg"), size: "M", colour: "black", price_cat: 1, user: julia } )
piece4 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "New Look", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "M", colour: "red", price_cat: 1, user: julia } )
piece5 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "DKNY", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "M", colour: "red", price_cat: 1, user: julia } )
piece6 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "C&A", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "S", colour: "red", price_cat: 1, user: julia } )
piece7 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "YAS", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "S", colour: "red", price_cat: 1, user: stella } )
piece8 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "b.Young", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "XS", colour: "red", price_cat: 1, user: stella } )
piece9 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "Rarcel", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "M", colour: "red", price_cat: 1, user: emma } )
piece10 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "Dynamo", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "M", colour: "red", price_cat: 1, user: emma } )
piece11 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "Diesel", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "XL", colour: "red", price_cat: 1, user: elisa } )
piece12 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "American Apperal", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "L", colour: "red", price_cat: 1, user: leda } )
piece13 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "Levi's", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "XL", colour: "red", price_cat: 1, user: leda } )
piece14 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "W.I.T.", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "L", colour: "red", price_cat: 1, user: louisa } )
piece15 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "Etsy", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "M", colour: "red", price_cat: 1, user: louisa } )
piece16 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "Look", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "S", colour: "red", price_cat: 1, user: hilda } )
piece17 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "React", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "XS", colour: "red", price_cat: 1, user: janna } )
piece18 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "H&M", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "S", colour: "red", price_cat: 1, user: janna } )
piece19 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "Twin Sister", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "M", colour: "red", price_cat: 1, user: pamina } )
piece19 = Piece.create( { name: "Ribbed Bodycon Mini Dress", brand: "Emma/Anna", image: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image3xxl.jpg"), image_b: open("http://images.asos-media.com/inv/media/1/5/0/8/6568051/image2xxl.jpg"), size: "M", colour: "red", price_cat: 1, user: pamina } )


piece1_p1 = Period.create( begin_date: "2016-08-15", end_date: "2016-10-30", piece: piece1 )
piece1_p2 = Period.create( begin_date: "2016-11-15", end_date: "2016-12-24", piece: piece1 )
piece2_p1 = Period.create( begin_date: "2016-09-01", end_date: "2016-10-15", piece: piece2 )
piece3_p1 = Period.create( begin_date: "2016-10-01", end_date: "2016-10-26", piece: piece3 )
piece4_p1 = Period.create( begin_date: "2016-09-15", end_date: "2016-12-01", piece: piece4 )
piece4_p2 = Period.create( begin_date: "2016-12-12", end_date: "2016-12-31", piece: piece4 )
piece5_p1 = Period.create( begin_date: "2016-08-15", end_date: "2016-11-21", piece: piece5 )
piece5_p2 = Period.create( begin_date: "2016-12-01", end_date: "2016-12-31", piece: piece5 )
piece6_p1 = Period.create( begin_date: "2016-09-03", end_date: "2016-09-27", piece: piece6 )
piece6_p2 = Period.create( begin_date: "2016-11-01", end_date: "2016-12-15", piece: piece6 )
piece7_p1 = Period.create( begin_date: "2016-08-15", end_date: "2016-12-30", piece: piece7 )
piece8_p1 = Period.create( begin_date: "2016-08-15", end_date: "2017-05-15", piece: piece8 )
piece9_p1 = Period.create( begin_date: "2016-08-15", end_date: "2016-11-15", piece: piece9 )
piece10_p1 = Period.create( begin_date: "2016-08-15", end_date: "2016-12-22", piece: piece10 )
piece11_p1 = Period.create( begin_date: "2016-08-15", end_date: "2016-12-31", piece: piece11 )
piece12_p1 = Period.create( begin_date: "2016-08-25", end_date: "2016-10-30", piece: piece12 )
piece13_p1 = Period.create( begin_date: "2016-08-23", end_date: "2016-12-01", piece: piece13 )
piece14_p1 = Period.create( begin_date: "2016-08-27", end_date: "2016-12-31", piece: piece14 )
piece15_p1 = Period.create( begin_date: "2016-08-12", end_date: "2016-10-30", piece: piece15 )
piece16_p1 = Period.create( begin_date: "2016-09-15", end_date: "2017-02-13", piece: piece16 )
piece17_p1 = Period.create( begin_date: "2016-10-15", end_date: "2017-04-30", piece: piece17 )
piece18_p1 = Period.create( begin_date: "2016-08-20", end_date: "2016-12-05", piece: piece18 )
piece19_p1 = Period.create( begin_date: "2016-08-26", end_date: "2016-12-31", piece: piece19 )
